FORMAT: 1A

# 4Bus API
HOST: http://4bus.com.br/api/

# Group Conexão
## Checagem de Autenticação de dispositivo [/]

### GET 
+ Request (application/json)
+ Response 200 (application/json)

        {
            "message": "4Bus",
            "status": "Connected"
        }
## Autenticação de dispositivo [/auth]

### POST

+ Request (application/json)
    + Attributes
        + imei (number)
        
+ Response 200 (application/json)        

        {
            "token": <token>,
            "company_name":<company_name>
        }
+ Response 406 (application/json)

        {
            "message":<errors>
        }
        
# Group Logs

## Log de Início e fim de viagem [/begin-end-trips]

### POST

+ Request Headers

        + Authorization: Bearer <token>,
        + Accept: application/json
    

+ Request (application/json)
    + Attributes
        + log (BeginEndTrip)

+ Response 200 (application/json)

        {
            "success":"Salvo"
        }
        
+ Response 406 (application/json)

        {
            "error":<message>
        }
## Log de Jornada de Trabalho [/journey]

### POST

+ Request Headers

        + Authorization: Bearer <token>,
        + Accept: application/json
        
+ Request (application/json)
    + Attributes
        + log (Journey)

+ Response 200 (application/json)

        {
            "success":"Salvo"
        }

+ Response 406 (application/json)

        {
            "message":<errors>
        }
## Log de Detecção de parada [/stop-detector]
  
### POST

+ Request Headers

        + Authorization: Bearer <token>,
        + Accept: application/json

+ Request (application/json)
    + Attributes
        + log (StopDetector)

+ Response 200 (application/json)

        {
            "success":"Salvo"
        }
        
+ Response 406 (application/json)

        {
            "message":<errors>
        }
# Group Checagem


## Checagem de viagens [/check-trips/{qtt}]
+ Attributes
    + plate (string)
+ Parameters
    + qtt - Quantidade de viagens atuais e ativas
    
### GET8
+ Response 200 (application/json)
    + Attributes
        + trips (array[Trip])
+ Response 406 (application/json)

        {
            "warning":<warning>
        }
+ Response 404 (application/json)

        {
            "error":"Placa inválida"
        }
    
# Data Structures

## Trip (object)
+ id: 123 (number)
+ leave: "2022-02-12 12:02:30 +0300"  (string)
+ arrive: "2022-02-12 12:02:30 +0300"   (string)
+ status: (number)
    00 - Realizada
    01 - Em andamento
    02 - Cancelada
    03 - Não iniciada
+ drivers (array[Driver])
+ destiny (City)
+ origin (City)
+ itineraries (array[Itinerary])
+ current_driver: (Driver) - Caso status em andamento (01) somente
+ current_direction: boolean
    00 - Indo
    01 - Voltando

## Itinerary (object)
+ id: 123 (number)
+ title: "Guanabara" (string)
+ description: "Descrição" (string)
+ lat: -168.59802 (number) - Latitude
+ lng: -168.59802 (number) - Longitude
+ order: 1 (number) - Ordem do Itinerário

## Driver (object)
+ cpf: "231.706.051-35" (string)
+ avatar:"/storage/driver/1be0d6d2fc74a74f3144dddc18a57985.jpeg" (string)
+ name: "José Maia" (string)

## City (object)
+ id: 123 (number)
+ name: "Brusque" (string)
+ abbr: "SC" (string)

## Base (object)
+ id_trips: 123 (number, required) - Código da viagem
+ lat: -168.59802 (number, required) - Latitude 
+ lng: -168.59802 (number, required) - Longitude
+ pdop: 2 (number, required) - PDOP (Position Dilution of Precision) 
+ dt: "2022-02-12 12:02:30 +0300" (string, required) - Data e Hora do Evento 
+ imei: 090938120938012830 (number, required)

## StopDetector (Base)
+ cmp (number, required) - Código de motivo de parada
    00 - parada programada
    01 - solicitação de passageiro
    02 - solicitação de motorista
    03 - solicitação externa
    04 - solicitação agente rodoviário ou fiscalização
    05 - acidente na via
    06 - acidente com o veículo
    07 - acidente com passageiro
    08 - defeito no veículo
    09 - troca programada de veículo
    10 - outro 
+ dsc: descrição da parada (string, required) - Descrição do motivo de parada

## Journey (Base)
+ unknown_driver: '098.634.849-03' (string, optional) - CPF do Motorista

## BeginEndTrip (Base)
+ cpf: '098.634.849-03' (string, required) - CPF do Motorista
+ trv  - Tipo do registro de viagem
    0 - Fim
    1 - Início
    2 - Fim com Transbordo
    3 - Início com Transbordo 
    
+ csl - Código do sentido da linha
    0 - Volta
    1 - Ida
